### ISSUE TITLE
Self Signed Certificate keeps giving sec_error_unknown_issuer on FF 49, sel beta 3 jar , gecko v.10.0file

### ISSUE THREAD

**Issue by sandeepjain1987** [gempesaw/Selenium-Remote-Driver#277]
I have manually accepted the ssl cert but I still get sec_error_unknown_issuer when a simple selenium script is run. Screenshot is attached
This is similar to issue : https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3586
Following is the script :

``` java
    public static void main(String[] args) throws Exception {
                      DesiredCapabilities capabilities = DesiredCapabilities.firefox();
                       capabilities.setBrowserName("firefox");
                  capabilities.setPlatform(Platform.WINDOWS);
                  WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"),            capabilities);
               driver.get("https://vv7.stealthstation.com/"); //This is my company's internal site
                       driver.quit(); 
                       driver.close();
}
```

Spec: Firefox 49 Selenium beta 3 jar file , gecko driver v.10.0
Selenium Logs: 

```
Exception in thread "main" org.openqa.selenium.WebDriverException: Error loading page (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 732 milliseconds
Build info: version: '3.0.0-beta3', revision: 'c7b525d', time: '2016-09-01 14:57:03 -0700'
System info: host: 'JAINS13-L3', ip: '10.29.82.194', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160905130425, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=20304, browserVersion=49.0, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt, device=desktop}]
Session ID: af80c582-dd52-4524-8694-f5bec11547f8
Command duration or timeout: 1.21 seconds
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: 'JAINS13-L3', ip: '10.29.82.194', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160905130425, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=20304, webdriver.remote.sessionid=3b41dd57-a526-4796-8455-08222449e8de, browserVersion=49.0, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, javascriptEnabled=true, platformName=windows_nt, device=desktop, cssSelectorsEnabled=true}]
Session ID: 3b41dd57-a526-4796-8455-08222449e8de
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:683)
    at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:331)
    at demo.testFirefoxSearch(demo.java:43)
    at demo.main(demo.java:23)
Caused by: org.openqa.selenium.remote.ScreenshotException: Screen shot has been taken
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: 'JAINS13-L3', ip: '10.29.82.194', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_92'
Driver info: driver.version: RemoteWebDriver
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:138)
    ... 4 more
Caused by: org.openqa.selenium.WebDriverException: Error loading page (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 732 milliseconds
Build info: version: '3.0.0-beta3', revision: 'c7b525d', time: '2016-09-01 14:57:03 -0700'
System info: host: 'JAINS13-L3', ip: '10.29.82.194', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160905130425, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=20304, browserVersion=49.0, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt, device=desktop}]
Session ID: af80c582-dd52-4524-8694-f5bec11547f8
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: 'JAINS13-L3', ip: '10.29.82.194', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_92'
Driver info: driver.version: EventFiringWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:631)
    at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:323)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
    at com.sun.proxy.$Proxy3.get(Unknown Source)
    at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:162)
    at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:40)
    at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:25)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

![vv server cert issue](https://cloud.githubusercontent.com/assets/3402619/18363743/f6879414-75d0-11e6-8b3f-4830e340aa45.png)

**Comment by gempesaw** [comment]
Hi Sandeep, thanks for making a new issue and providing all the information. It's all quite useful stuff! I appreciate it. This repository is specifically for the perl bindings to webdriver; your issue being in Java means you may have luck also asking at the official webdriver users group: https://groups.google.com/forum/#!forum/webdriver

I suspect there is a Firefox profile setting that we can set to disable security checks, but I don't know what it is off the top of my head. I've a meeting to run to, but I'll try to look up the setting when I have time. Cheers!

**Comment by sandeepjain1987** [comment]
Thanks for referring the google group for webdriver related issues. I tried the Firefox profile setting as well to disable security checks but that dint work :( . Fingers crossed. Appreciate your help.

**Comment by dmitrytokarev** [comment]
Related/duplicate to https://github.com/mozilla/geckodriver/issues/93

**Comment by gempesaw** [comment]
Thanks dmitry, looks like this issue duplicates the linked issue, so hopefully they resolve it in geckodriver soon! c:

**Comment by gempesaw** [comment]
looks like this has been resolved in an upcoming firefox beta, one of the FF contributors helpfully wrote up a [blog post](https://www.hskupin.info/2017/01/23/using-selenium-and-webdriver-to-interact-with-insecure-ssl-pages-in-firefox/) explaining the usage.

Looks like you need to use FF52, and the preference name is `acceptInsecureCerts`. Good luck!
